name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: xcodebuild -scheme MCSC -configuration Release build

      - name: Debug Build Directory
        run: find . -name "*.app"

      - name: Zip App
        run: |
          APP_PATH=$(find . -name "MCSC.app" -type d | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "MCSC.app not found!"
            exit 1
          fi
          zip -r MCSC.zip "$APP_PATH"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: MCSC.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
