name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: xcodebuild -scheme MCSC -configuration Release -derivedDataPath build build

      - name: Zip App
        run: |
          APP_PATH="build/Build/Products/Release/MCSC.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "MCSC.app not found at $APP_PATH!"
            exit 1
          fi
          cd build/Build/Products/Release
          zip -r ../../../MCSC.zip MCSC.app

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: MCSC.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
